# Generated by Django 4.2.1 on 2023-08-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='email',
            field=models.EmailField(default='satish8899@gmail.com', max_length=254),
        ),
    ]
